version: "3.3"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - status-service
      - story-service

  
  # frontend:
  #   build: ./FrontEnd
  #   image: inz/frontend
  #   restart: unless-stopped
  #   ports:
  #       - 4200:4200
  #   depends_on:
  #       - nginx

  db-users:
    image: mongo:latest
    volumes:
      - users:/data/db

  db-status:
    image: mongo:latest
    volumes:
      - status:/data/db

  db-story:
    image: mongo:latest
    volumes:
      - storynew:/data/db


  storyobjectdb:
    image: minio/minio:latest
    ports:
        - 9000:9000
        - 9001:9001
    environment:
        - MINIO_ROOT_USER=minioadmin
        - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
    volumes:
        - object:/data


  user-service:
    build: ./User_Service
    restart: unless-stopped
    depends_on:
      - db-users

  status-service:
    build: ./Status_Service
    restart: unless-stopped
    depends_on:
      - user-service
      - db-status
 

  story-service:
    build: ./Story_Service
    restart: unless-stopped
    depends_on:
      - db-story
      - user-service
      - storyobjectdb

volumes:
  status:
  users:
  object:
  storynew: