version: "3.9"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - status-service
      - story-service

  
  frontend:
    container_name: frontend
    build: ./FrontEnd
    image: muktar16/frontend
    restart: unless-stopped
    ports:
        - 4200:4200
    depends_on:
        - nginx

  db-users:
    image: mongo:latest
    # ports:
    #   - 27020:27017
    volumes:
      - users:/data/db

  db-status:
    image: mongo:latest
    # ports:
    #   - 27018:27017
    volumes:
      - status:/data/db

  db-story:
    image: mongo:latest
    # ports:
    #   - 27019:27017
    volumes:
      - storynew:/data/db


  storyobjectdb:
    container_name: storyobjectdb
    image: minio/minio:latest
    ports:
        - 9000:9000
        - 9001:9001
    environment:
        - MINIO_ROOT_USER=minioadmin
        - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
    volumes:
        - object:/data



  user-service:
    container_name: userservice
    build: ./User_Service
    image: muktar16/userservice
    restart: unless-stopped
    # ports:
    #   - 3000:3000
    depends_on:
      - db-users
    # environment:
    #   MONGODB_URI: mongodb://db-users:27017/UserDatabase

  status-service:
    container_name: statusservice
    build: ./Status_Service
    image: muktar16/statusservice
    restart: unless-stopped
    # ports:
    #   - 3001:3001
    depends_on:
      - user-service
      - db-status
    # environment:
    #   MONGODB_URI: mongodb://db-status:27017/StatusDatabase
 

  story-service:
    container_name: storyservice
    build: ./Story_Service
    
    image: muktar16/storyservice
    restart: unless-stopped
    # ports:
    #   - 3002:3002
    depends_on:
      - db-story
      - user-service
      - storyobjectdb
    # environment:
    #   MONGODB_URI: mongodb://db-story:27017/StoryDatabases


volumes:
  status:
  users:
  object:
  storynew: